name: machine_task_atts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
